artifacts_root: artifacts

data_ingestion:
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion